version: "2"

services:
  mongo:
    image: mongo:4.4.0
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - network-vpc

  jumbo-app-backend:
    build:
      context: stores-finder-backend
    image: jumbo/store-finder-backend
    environment:
      # Overrides the host in the Spring Boot application to use the Docker's hostname
      - SPRING_DATA_MONGODB_HOST=mongo
    ports:
      - "8080:8080"
    networks:
      - network-vpc

  jumbo-app-frontend:
    build:
      context: stores-finder-frontend
    image: jumbo/store-finder-frontend
    ports:
      - "4000:3000"
    networks:
      - network-vpc

volumes:
  mongodata:

networks:
  network-vpc:
